#!/usr/bin/env bash
icons=(




)
full_icon=battery-full-charging-symbolic.symbolic
low_icon=battery-caution-symbolic.symbolic
NID=$$

print() {
    printf '<span size="21pt"><tt>%s</tt></span> <span rise="5pt">%s%%</span>\n' \
        "$1" "$2"
}

while :;do
    capacity=$(< /sys/class/power_supply/BAT?/capacity)
    _status=$(< /sys/class/power_supply/BAT?/status)
    case "$_status" in
        Charging)
            if [ "$capacity" -gt 90 ];then
                dunstify -r "$NID" -i "$full_icon" \
                    "Battery charged!" "$(acpi)"

                print "$i" "$capacity"
                sleep $(( 60 * 5 ))
            else
                for i in "${icons[@]}";do
                    print "$i" "$capacity"
                    sleep 1.5
                done
            fi
        ;;
        Not?charging)
            printf 'U %s%%\n' "$capacity"
        ;;
        *)
            i=0
            if [ "$capacity" -ge 90 ];then
                i=3
            elif [ "$capacity" -ge 60 ];then
                i=2
            elif [ "$capacity" -ge 30 ];then
                i=1
            fi
            print "${icons[i]}"  "$capacity"
            if [ "$capacity" -lt 20 ];then
                dunstify -r "$NID" -i "$low_icon" \
                    "Battery discharging!" "$(acpi)"
            fi
        ;;
    esac
    sleep 60
done
