#!/usr/bin/env bash
capacity=$(< /sys/class/power_supply/BAT?/capacity)
_status=$(< /sys/class/power_supply/BAT?/status)
full_icon=battery-full-charged
low_icon=battery-low

case "$_status" in
    Charging)
        if [ "$capacity" -gt 90 ];then
            printf 'CHR %s%%\n' \
                "$capacity"
            notify-send -i "$full_icon" \
                "Battery charged!" "$(acpi)"
        else
            printf 'CHR %s%%\n' "$capacity"
        fi
    ;;
    *)
        if [ "$capacity" -lt 20 ];then
            printf 'BAT %s%%\n' "$capacity"
            notify-send -i "$low_icon" \
                "Battery discharging!" "$(acpi)"
        else
            printf 'BAT %s%%\n' "$capacity"
        fi
    ;;
esac
