#!/usr/bin/env bash
ICON=xfce4-clipman-plugin
song=$(cat /tmp/.cmus-status)
case "$BLOCK_BUTTON" in
    1|2)
        notify-send -i "$ICON"  "Clipboard" "$song"
        printf '%s' "$song" | xclip -sel clip >/dev/null 2>&1
    ;;
esac
[ ${#song} -gt 80 ] && song=${song::80}...
[ -n "$song" ] && echo " ♪ $song "
