#!/bin/sh
ICON=/usr/share/icons/Chicago95/apps/32/xfce4-clipman-plugin.png
current_song() {
    cmus-remote -Q 2>&1 | awk '{
    if ($0 ~ /cmus is not running/) exit
    if ($0 ~ /^file/) { split($0, a, "/"); file = a[length(a)]; }
    if ($0 ~ /^tag title/) { sub(/(\w* ){2}/, "", $0); title = $0 }
    if ($0 ~ /^tag artist/) { sub(/(\w* ){2}/, "", $0); artist = $0 }
    } END {
        if ( !title ) title = file
        if ( length(title) > 40 ) title = substr(title, 1, 37)"..."
        if ( !title ) exit
        printf("%s - %s", artist, title)
    }'
}
title=$(current_song)
if test -n "$BLOCK_BUTTON";then
    notify-send -i "$ICON"  "Copied to clipboard" "$title"
    echo -n "$title" | xclip -sel clip >/dev/null 2>&1
fi
[ -n "$title" ] && echo " ♪ ${title//\&/and} "

exit 0
