#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
    1|2) alacritty --class floating_terminal -e top  ;; 
esac

cpu_file=/tmp/.cpu_usage
if [ -f $cpu_file ];then
    IFS=' ' read -r -a arr < $cpu_file
fi
PREV_TOTAL=${arr[0]:-0}
PREV_IDLE=${arr[1]:-0}

# Get the total CPU statistics, discarding the 'cpu ' prefix.
CPU=($(sed -n 's/^cpu\s//p' /proc/stat))
IDLE=${CPU[3]} # Just the idle CPU time.

# Calculate the total CPU time.
TOTAL=0
for VALUE in "${CPU[@]:0:8}"; do
    TOTAL=$((TOTAL+VALUE))
done

# Calculate the CPU usage since we last checked.
DIFF_IDLE=$((IDLE-PREV_IDLE))
DIFF_TOTAL=$((TOTAL-PREV_TOTAL))
DIFF_USAGE=$(((1000*(DIFF_TOTAL-DIFF_IDLE)/DIFF_TOTAL+5)/10))

printf 'CPU %2d%%\n' "$DIFF_USAGE"

# Remember the total and idle CPU times for the next check.
[ -f "$cpu_file" ] && rm -f "$cpu_file"
echo "$TOTAL $IDLE" > "$cpu_file"
