#!/bin/sh
[ "$BLOCK_BUTTON" -eq 1 ] && xterm -name floating_terminal -e \
    bash -c 'df -hT -x tmpfs -x devtmpfs; read -sn1'

df -h -x tmpfs -x devtmpfs | awk '!/^Filesystem|\/boot$/{
    if ($6 != "/") {
        split($6, a, "/")
        mp = a[length(a)]
    } else {
        mp = $6
    }
    printf("[%s %s] ", mp, $4)}
' | sed 's/^/ /;'
echo
