#!/bin/sh

# echo -n " "
# find /sys/devices -type d -path '*hwmon[0-9]*' ! -path '*power*' | while read -r d
# do
#     device=$(< "$d"/name)
#     [ "$device" = "acpitz" ] && continue
#     temp=$(awk '{avg+=($1 / 1000); n+=1}END{printf("%0.f", avg / n)}' "$d"/temp*_input)
#     echo -n "$device: $temp°C "
# done
# echo

wifi=$(awk '{avg+=($1 / 1000); n+=1} END {printf("%0.f", avg / n)}' \
    /sys/devices/virtual/thermal/thermal_zone1/hwmon?/temp*_input)
cpu=$(awk  '{avg+=($1 / 1000); n+=1} END {printf("%0.f", avg / n)}' \
    /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp*_input)
echo "CPU $cpu°C WIFI $wifi°C"
