#!/bin/sh
case "$BLOCK_BUTTON" in
    1|2) xterm -geometry 20x9-10+25 -name floating_terminal -e 'cal; read -N 1 -s' ;;
    3) xterm -geometry 69x35-10+25 -name floating_terminal -e 'cal -y; read -N 1 -s' ;;
esac

#date +' %b %d %H:%M ' # Jun 21 22:10
date +'%H:%M'
