#!/bin/sh
case "$BLOCK_BUTTON" in
    1|2) ts -g 22x9  -n floating_window -- 'cal; read -N 1 -s'    ;;
    3)   ts -g 70x35 -n floating_window -- 'cal -y; read -N 1 -s' ;;
esac

date +'<span size="11pt"> %b %d %Y %H:%M </span>' # Jun 21 22:10
# date +' %H:%M %d/%m/%Y '
