#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
    1|2) alacritty --class floating_terminal -e pulsemixer ;;
    3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    5|6) volupdown.sh up ;;
    4|7) volupdown.sh down ;;
esac

vol=$(pactl list sinks | awk '/^[ \t]*Volume:/{print substr($5, 1, length($5)-1)}' | head -1)
if [ "$vol" -le 5 ] || pactl list sinks | grep -q 'Mute: yes';then
    i="婢"
else
    if [ "$vol" -ge 50 ];then
        i=""
    elif [ "$vol" -gt 1 ];then
        i="" 
    else
        i=""
    fi
fi
printf '<span size="18pt"><tt>%s</tt></span> %s%%\n' "$i" "$vol"

exit 0
