#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
    1|2) alacritty --class floating_terminal -e pulsemixer ;;
    3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    5|6) volupdown.sh up ;;
    4|7) volupdown.sh down ;;
esac

volume=$(pactl list sinks | awk '/^[ \t]*Volume:/{print substr($5, 1, length($5)-1)}' | head -1)
if [ "$volume" -le 5 ] || pactl list sinks | grep -q 'Mute: yes';then
    echo "婢"
else
    if [ "$volume" -ge 50 ];then
        echo " ${volume}%"
    elif [ "$volume" -gt 1 ];then
        echo " ${volume}%" 
    else
        echo " ${volume}%"
    fi
fi

exit 0
