#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
    1|2) alacritty --class floating_terminal -e pulsemixer ; exit 0 ;;
    3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    5|6) volupdown.sh up ;;
    4|7) volupdown.sh down ;;
esac

volume=$(pactl list sinks | awk '/^[ \t]*Volume:/{print substr($5, 1, length($5)-1)}' | head -1)
if [ "$volume" -le 5 ] || pactl list sinks | grep -q 'Mute: yes';then
    echo "MUTED"
else
    #dunstify -r 8899 -i audio-volume-high -h "int:value:$volume" "Volume" 
    printf 'VOL %s%%\n' "${volume}" 
fi

exit 0
