#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
    1|2) alacritty --class floating_terminal -e pulsemixer ;;
    3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    5|6) volupdown.sh up ;;
    4|7) volupdown.sh down ;;
esac

get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ | awk '/^[ \t]*Volume:/{print substr($5, 1, length($5)-1); exit}'
}
volume=$(get_volume)
[ -z "$volume" ] && sleep 5 && volume=$(get_volume)
if [ "$volume" -lt 5 ] || pactl list sinks | grep -q 'Mute: yes';then
    # printf 'M %s%%\n' "${volume}"
    echo 󰖁
elif [ -n "$volume" ];then
    printf '  %s%%\n' "${volume}" 
fi

exit 0
