#!/bin/sh
# https://saucenao.com/user.php?page=search-api
API_KEY=$(cat ~/.config/.sauce 2>/dev/null)

tmpfile=$(mktemp)
end() { rm "$tmpfile"; }
trap end EXIT

rotate() {
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort -u | while read -r file; do
        case "$(file -b -i "$file")" in
            image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
            *) mogrify  -rotate "$degree" "$file" ;;
        esac
    done
}

sauce() {
    r=$(curl -L -X POST -F file=@"$1" "https://saucenao.com/search.php?output_type=2&api_key=$API_KEY" |
        jq -r '.results[0].data | if .ext_urls then .ext_urls[0] else .source end')

    case "$r" in
        http*) $BROWSER "$r" >/dev/null 2>&1 & ;;
        *)  printf '%s' "$r" | xclip -sel clip
            notify-send 'Copied to clipboard' "$r" ;;
    esac
}

case "$1" in
    comma)  rotate 270 ;;
    period) rotate  90 ;;
    slash)  rotate 180 ;;
    i) while read -r i;do mogrify -flip "$i" ;done ;;
    o) while read -r i;do mogrify -flop "$i" ;done ;;
    d) while read -r i;do rm -v "$i" ;done ;;
    # n) read -r f; rm -rfv "${f%/*}" ;; # dangerous!
    n) read -r f; alacritty -e nnn "${f%/*}" & ;;
    g) read -r f; setsid -f -- gimp "$f" >/dev/null 2>&1 & ;;
    w) head -1 | xargs -I{} xwall.sh '{}' ;;
    p) head -1 | tr \\n \\0 | xargs -0 realpath -- | tr -d \\n | xclip -sel clip ;;
    b) head -1 | tr \\n \\0 | xargs -0 basename -- | tr -d \\n | xclip -sel clip ;;
    v) head -1 | tr \\n \\0 | xargs -0 dirname -z | xargs -0 nsxiv -s w -bqr & ;;
    # v) head -1 | tr \\n \\0 | xargs -0 vbg.sh ;;
    s) while read -r i;do sauce "$i" ;done ;;
    T) tr \\n \\0 | xargs -0I{} trash.sh '{}' ;;
    P) grep -oP '[^/]*\.(mkv|webm|mp4|avi|m4v)(?=\.\w+)' | mpv --playlist=- >/dev/null 2>&1 ;;
    x)
        read -r file
        notify-send "$file copied to clipboard"
        if [ "${file##*.}" != "png" ];then
            magick "$file" PNG:- | xclip -sel clip -target image/png
        else
            xclip -sel clip -target image/png "$file"
        fi
    ;;
    m|y)
        cat > "$tmpfile"
        target=$(find ~/Pictures -xdev -type d | dmenu -c -l 15 -i)
        [ -z "$target" ] && exit 0
        while read -r i;do
            if [ "$1" = m ];then
                mv -vn "$i" "$target"
            else
                cp -vn "$i" "$target"
            fi
        done < "$tmpfile"
    ;;
    u)
        head -1 | tr \\n \\0 | xargs -r0I{} curl -F'file=@{}' https://0x0.st | xclip -sel c
        notify-send "Clipboard" "$(xclip -sel c -o)"
    ;;
esac
