#!/bin/sh
tmpfile=$(mktemp)
end() { rm "$tmpfile"; }
trap end EXIT

rotate() {
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort -u | while read -r file; do
        case "$(file -b -i "$file")" in
            image/jpeg*)
                jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
            *) mogrify  -rotate "$degree" "$file" ;;
        esac
    done
}

case "$1" in
    d) while read -r i;do rm -v "$i" ;done ;;
    w) xargs -rI{} xwall.sh '{}' ;;
    f) xargs -rI{} xwall.sh --focus '{}' ;;
    t) xargs -rI{} xwall.sh --tile '{}' ;;
    T) xargs -rI{} trash.sh '{}' ;;
    P) grep -oP '[^/]*\.(mkv|webm|mp4|avi)(?=\.\w+)' | mpv --playlist=- --really-quiet=yes >/dev/null 2>&1 ;;
    p) head -1 | tr \\n \\0 | xargs -0 realpath | tr -d \\n | xclip -sel clip ;;
    v) head -1 | tr \\n \\0 | xargs -r0 vbg.sh ;;
    g) read -r f; gimp "$f" & ;;
    n) read -r f; alacritty -e nnn "${f%/*}" & ;;
    x)
        read -r file
        if [ "${file##*.}" != "png" ];then
            convert "$file" PNG:- | xclip -sel clip -target image/png
        else
            xclip -sel clip -target image/png "$file"
        fi
    ;;
    m|y)
        cat > "$tmpfile"
        target=$(find ~ -xdev -maxdepth 5 -type d \! -path '*/\.*' | dmenu -c -l 15 -i)
        [ -z "$target" ] && exit 0
        while read -r i;do
            if [ "$1" = m ];then
                mv -vn "$i" "$target"
            else
                cp -vn "$i" "$target"
            fi
        done < "$tmpfile"
    ;;
    u)
        head -1 | tr \\n \\0 | xargs -r0I{} curl -F'file=@{}' https://0x0.st | xclip -sel c
        notify-send -i xfce4-clipman-plugin "Clipboard" "$(xclip -sel c -o)"
    ;;
    comma)  rotate 270 ;;
    period) rotate  90 ;;
    slash)  rotate 180 ;;
esac
