#!/bin/sh
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n
SELECTION="$HOME/.config/nnn/.selection"

if [ -s "$SELECTION" ];then
    xargs -r0I{} basename '{}' < "$SELECTION"
else
    echo -n "$1"
fi | xclip -sel clip
