#!/usr/bin/env bash

NNN_FIFO=${NNN_FIFO:-/tmp/nnn.fifo}
PREVIEW_PID=/tmp/nnn_preview.pid
if [ -e "$NNN_FIFO" ] && [ -f "$PREVIEW_PID" ];then
    echo hide > "$NNN_FIFO"
    trap 'echo unhide > $NNN_FIFO' EXIT
fi

PAGER=${PAGER:-less -Ri}

mime=$(file -Lbi -- "$1")
case "${mime%%;*}" in
    audio/*|video/*|image/gif) mpv "$1" ;;
    image/*) nsxiv -q "$1" >/dev/null 2>&1 ;;
    text/*)  ${EDITOR:-vi} "$1" ;;
    *) false ;;
esac && exit 0

tmp=$(mktemp -d)
trap 'rm -rf "${tmp}"' EXIT
open() {
    if [ -n "$TMUX" ];then
        tmux split-window -h "nnn ${tmp}"
    else
        xdg-open "${tmp}" &
    fi
}

#7z) 7z l -p -- "$1" | $PAGER ;;
ext=$(printf '%s' "${1##*.}" | tr '[:upper:]' '[:lower:]')
case "$ext" in
    tar)    open; tar axf "$1" -C "${tmp}"  ;;&
    zip|7z) open; 7z x -o"${tmp}" "$1"      ;;&
    rar)    open; unrar x -op"${tmp}" "$1"; unrar lt -p- -- "$1" | $PAGER ;;
    a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rpm|rz|t7z|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|tar|zip|7z)
        atool --list -- "$1" | $PAGER
        ;;
    htm|html|xhtml) w3m -dump "$1" | $PAGER     ;;
    torrent) xdg-open "$1" >/dev/null 2>&1 &    ;;
    json) jq --color-output . "$1" | $PAGER     ;;
    md) bat --color=always "$1" ;;
    cbz|pdf|epub) zathura "$1" ;;
    mts) mpv "$1" ;;
    exe) wine "$1" ;;
    ass|srt|vtt) setsid -f -- aegisub "$1" >/dev/null 2>&1 ;;
    *) exit 0 ;;
esac
