#!/usr/bin/env bash
# shellcheck disable=SC2317

#
# nnn SimplePreView 
#

[ -z "$TMUX" ] && { printf '\n$TMUX not set\n'; sleep 1; exit 1; } 

PREVIEW_PID=/tmp/nnn_preview.pid
FIFO_PID=/tmp/nnn_fifo.pid
NNN_FIFO=${NNN_FIFO:-/tmp/nnn.fifo}
PREVIEW_SIZE=60%

pidkill() { [ -f "$1" ] && kill "$(cat "$1")" >/dev/null 2>&1; }
fifo_pager() {
    cmd="$1"
    shift

    # We use a FIFO to access $PAGER PID in jobs control
    tmpfifopath=$(mktemp --dry-run)
    mkfifo "$tmpfifopath" || return

    less -P?n -R -C --mouse < "$tmpfifopath" &
    printf "%s" "$!" > "$PREVIEW_PID"

    (
        exec > "$tmpfifopath"
        if [ "$cmd" = "bat" ];then
            bat --terminal-width="$cols" --color=always --paging=never \
                --style="$BAT_STYLE" --theme="$BAT_THEME" "$@"
        else
            "$cmd" "$@"
        fi &
    )

    rm "$tmpfifopath"
}
handle_mime() {
    mime=$(file -Lbi -- "$1" | cut -d';' -f1)
    case "$mime" in
        image*|video*) mediainfo -- "$1" ;;
        text/*) fifo_pager bat "$1" ;;
        */x-bittorrent) fifo_pager aria2c -S "$1" ;;
        *) file -b -- "$1" ;;
    esac
}
handle_ext() {
    ext=$(printf '%s' "${1##*.}" | tr '[:upper:]' '[:lower:]')
    case "$ext" in
        srt) fifo_pager bat "$1" ;;
        json) fifo_pager jq -C . "$1" ;;
        gz) fifo_pager gunzip -l "$1" ;;
        7z|a|ace|alz|arc|arj|bz|cab|cpio|deb|jar|lha|lz|lzh|lzma|lzo\
        |rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)
            fifo_pager atool -l "$1" ;;
        *) handle_mime "$1" ;;
    esac
}
preview() {
    clear
    cols=$(tput cols)
    if [ -d "$1" ];then
        fifo_pager tree -C -L 1 --dirsfirst "$1"
    else
        handle_ext "$1"
    fi
}
preview_fifo() {
    while read -r sel; do
        case "$sel" in
            close) break ;;
            hide) tmux new -d -s tmp sleep 1 \; movep -s 1 -t tmp ;;
            unhide) tmux joinp -l "$PREVIEW_SIZE" -h -d -s tmp -t 1 ;;
            *)
                pidkill "$PREVIEW_PID"
                [ -n "$sel" ] && preview "$sel" ;;
        esac
    done < "$NNN_FIFO"
}
end() {
    jobs -p | xargs -r kill
    rm "$PREVIEW_PID" "$FIFO_PID" 2>/dev/null
}

if [ "$PREVIEW_MODE" ];then
    preview "$1"
    preview_fifo &
    printf '%s' "$!" > "$FIFO_PID"
    trap end EXIT INT HUP
    wait "$!" 
else
    if pidkill "$FIFO_PID";then
        pidkill "$PREVIEW_PID"
    else
        tmux split-window -h -d -l "$PREVIEW_SIZE" \
            -e "NNN_FIFO=$NNN_FIFO" -e "PREVIEW_SIZE=$PREVIEW_SIZE" \
            -e "FIFO_PID=$FIFO_PID" -e "PREVIEW_PID=$PREVIEW_PID" \
            -e "BAT_STYLE=$BAT_STYLE" -e "BAT_THEME=$BAT_THEME" \
            -e "PREVIEW_MODE=1" "$0" "$1" &
    fi
fi

exit 0
