#!/bin/sh
e='.*\.(mkv|webm|flv|avi|ts|mts|m2ts|mov|mp4|m4v|gif)'
if [ -d "$1" ];then
    find "$1" -maxdepth 4 -regextype posix-extended -iregex "$e" |
        sort -V | mpv --playlist=-
else
    mpv "$PWD"
fi
