#!/bin/sh
fvideo() {
    find "${1:-.}" -maxdepth 3 \
        -iregex '.*\.\(mkv\|webm\|flv\|ogv\|ogg\|avi\|ts\|mts\|m2ts\|mov\|wmv\|rmvb\|mp4\|m4v\|m4p\|mpg\|mpeg\|3gp\|gif\)$' | sort -V
}

if [ -d "$1" ];then
    fvideo "$1" | mpv --playlist=-
else
    mpv "$PWD"
fi
